# Generated by Django 3.1.5 on 2021-03-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense_type',
            new_name='Ename',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='income_type',
            new_name='Iname',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='receipt_type',
            new_name='name',
        ),
    ]
