# Generated by Django 3.1.5 on 2021-03-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0002_auto_20210304_2144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
