# Generated by Django 3.1.5 on 2021-03-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0004_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='sub_treatment',
        ),
    ]
