# Generated by Django 3.1.7 on 2021-03-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0005_remove_treatment_sub_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
