# Generated by Django 3.1.7 on 2021-04-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0010_auto_20210410_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='income',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='medicalId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
