# Generated by Django 3.1.7 on 2021-04-11 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0011_auto_20210411_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Forms.doctor'),
        ),
        migrations.AddField(
            model_name='income',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Forms.doctor'),
        ),
    ]
