# Generated by Django 3.1.7 on 2021-04-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0013_auto_20210411_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
