# Generated by Django 3.1.5 on 2021-04-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0014_auto_20210413_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedbackType', models.CharField(max_length=10, null=True)),
                ('FeedbackDescription', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
